apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name | dump }}
  annotations:
    aws.amazon.com/aws-codepipeline: arn:aws:codepipeline:${{ values.region }}:${{ values.account_id }}:${{ values.name }}
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  owner: user:guest
  lifecycle: experimental